FROM python:3.9-slim
WORKDIR /app
COPY llm_service/requirements.txt .
RUN pip install -r requirements.txt
COPY llm_service/ .
COPY database/db.py database/
CMD ["uvicorn", "llm:app", "--host", "0.0.0.0", "--port", "8000"]