FROM python:3.9-slim
WORKDIR /app
COPY web_interface/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY web_interface/backend/main.py .
COPY database/db.py ./database/
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]